apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/sugesh-cloudops/EKS-Terraform-Nginx/"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true