FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/target/springboot-postgres-0.0.1-SNAPSHOT.jar app.jar
CMD ["java", "-jar", "app.jar"]