---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-01
  namespace: test-deploy
spec:
  selector:
    matchLabels:
      app: test-deploy-01
  template:
    metadata:
      labels:
        app: test-deploy-01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"