apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  template:
    spec:
      containers:
        - name: springboot-postgres
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev