apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-postgres
  template:
    metadata:
      labels:
        app: springboot-postgres
    spec:
      containers:
      - name: springboot-postgres
        image: sugesh23/springboot-postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: mydb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: mysecretpassword

        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 3

        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   failureThreshold: 5