apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-postgres
  template:
    metadata:
      labels:
        app: springboot-postgres
    spec:
      containers:
      - name: springboot-postgres
        image: sugesh23/springboot-postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            value: postgres-0.headless-svc.default.svc.cluster.local
          - name: DB_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: mydb
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: mysecretpassword