apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-postgres
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional: fixed external port
  type: NodePort